# Installing up-to-date Erlang requires root
sudo: true
dist: trusty
addons:
    postgresql: "9.6"
    hosts:
        - mediacloud.local
language: generic
matrix:
    include:
        - os: linux
          language: perl
          perl: 5.22
cache:
    directories:
        # Carton dependencies
        - local/
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
env:
    global:
        # Facebook Graph API credentials for testing:
        # * MC_FACEBOOK_APP_ID
        # * MC_FACEBOOK_APP_SECRET
        - secure: "TklAqxPSqywPk5khp54R7iYW9jGfuWYiVC7xY3wiO8GQHRpW3b0a6zR3yEbeBMvKMt5b1IaCCJwuyasP/W0xPopqozqJFr/6045/tfTqRQ7/Bo6noJ1a640yLjjDzlGenHqkTCbhp5y4kaT2BS1IoTi423FOXQB1OVTpVD55jAw="
        - secure: "A9bwQIK5W8VyQlpdnoA6LhKTcllytTS/8ueyzi9Y7F6xFdD2sFnfTy6UgpFIzgtVezYJYqy7Wcr1RiC3ybOmsE4FSYRTptrEdu4Pf/nI/LRxDE+sF2kPDGrXRD8iTL5+K2h5DMbBG2NsoflC+qRgn1W9f/Ey1gMsmCyOJJCnufw="
        # Amazon S3 test bucket credentials:
        # * MC_AMAZON_S3_TEST_ACCESS_KEY_ID
        # * MC_AMAZON_S3_TEST_SECRET_ACCESS_KEY
        # * MC_AMAZON_S3_TEST_BUCKET_NAME
        # * MC_AMAZON_S3_TEST_DIRECTORY_NAME
        - secure: "DpYY9zJCMOABwBUhW5tTLRjWgKKNgkWBH/i5x2hJTSkY53erpaaqTPzs/loGbiV1Q+TUu0PWPqRQh9eovDKd2/l2taXECbQi+gY/VprlYK4rqruLXci9mxJepIp9imITiCwxZB9hYI3BDxQYBvPDx0coklEi5bG017HZNlwYQfg="
        - secure: "ONqZb6dPH8uNcCVkLH722JPhP4Zua8QjbYcj24ob27LVrjh9UbSAUVMu+3XVczY0dERsGGcqH2bhaG3WYINAs0wnbyPfbAokHtRSrIcDfSfVkDfCzJkYl7jc1Dhc/lV/pe6ygqtGZQG+Whx/dKf6DpCJmpEekeHavwVDxzC1D+4="
        - secure: "Y3poZS6KCMfAyXmAG4hvHhCtaUHLl3UwB2CYjDLp2ki86tDtG7JfEJp2Q/8C610nzBw6WlA8bdljM9dxNHR6aEGHPxLz1NsGMLw8xYZFoMrw6RMpRq6BLcraylAmVZAFC2GTClqzHMWfW6mCQ5a5OznUWsJ6n4tP0aoPLjRpUgw="
        - secure: "GHU56Kl7zaE00MZeaPqie3e8xoxLaGnh3A03xZbG8/707tPtBsPLfPDaCSQf9PSstajVjPik+tUNuOTgyz9AD5ma3dwPdJ6VhpFNS/DD8+CDlojmgEfuvaVD7Bi3sLFuop/PWrNoi0pND45lv8O8shQ1WruHEWPgYxW10vd3Q7Y="
        # Univision API test credentials:
        # * MC_UNIVISION_TEST_URL
        # * MC_UNIVISION_TEST_CLIENT_ID
        # * MC_UNIVISION_TEST_CLIENT_SECRET
        - secure: "OJQnQvZNiusSPuHDndQfPjuNW5Gp3MlzfC/d91YIdh4ftyCso8Jy1LInetml2yNhSnTVe86sCarZ4v4f3/5wfkCuJc5Y7ph0Ij6LfqXdPhVSe+HsxQoAA60EbmcH0Ho/K3Y7LZOV+dqvWcvkrfdYPUQB9Qid2tHJYv4+JndycNM="
        - secure: "U4UiJwK5fsezvZOGsgW0v6hPiqXGor0Er6DAtlb7AE/qBx5j4goHYi4SsjMGX21pzFxlo+MmT6oGFj1rDf4uoF6TXW5UZn2fLsCYXrHRaQ7hJXog+tSw7CpAoR6mlXfxti6I83ln53GIgqhpzoZXscdS21r0q/vv8aFRT7dD8Ec="
        - secure: "Fw42BMs0PDUn3ouHbeDwps28BolRQuLcHtvax25sbFd6novSIpns/01c31pZy8LkOYSb0fDqnrx3zTYh468CctJks4cDRPTn8xjPMGP5mnrOxdQbVHLFD5nqo/bpOzvdUmBWj8t7r96C8x6PNqxfsQqeinzHi1e2wMbDyxGdFHQ="
        # Superglue test feed URL:
        # * MC_SUPERGLUE_TEST_URL
        - secure: "BzZcSjsuihkDowYPRz0F2HRiZ9LbEJkPXJpL8sRTBp1exbKAyfQ2+pXm3k2d34utp/gNiLlL+GFDmm7dr9wZ82DSqouBC8UJa3gaL/AeBrdXngaJbBeUqIWiDhsZFkf5F3V0J3r+7CxEAQVhU8hAPE7LB4VFjSYgXGZfoAMcdCw="
        # Do not ask for confirmation when running ./script/mediawords_create_db.pl
        - MEDIAWORDS_CREATE_DB_DO_NOT_CONFIRM=1
        # let tests know that they are running on travis
        - MC_SKIP_RABBIT_OPEN_FILES_LIMIT_CHECK=1
before_install:
    # Install APT packages (not PostgreSQL though)
    - ./install/install_mediacloud_package_dependencies.sh
    # Install Japanese language support library
    - ./install/install_mecab-ipadic-neologd.sh
    # Install Python dependencies
    - travis_retry ./install/install_python_dependencies.sh
    # Set up kernel and PostgreSQL parameters
    - ./install/set_kernel_parameters.sh
    - ./install/set_postgresql_parameters.sh
    # Create + switch to the Media Cloud's Perlbrew library
    - perlbrew lib create mediacloud
    - perlbrew switch @mediacloud
    # Set up Perl and module dependencies (dependencies might be restored from
    # cache into "local/" already in which case we just check if Carton is
    # happy with the current setup)
    - ./install/install_mc_perlbrew_and_modules.sh
install:
    # Use default configuration
    - cp mediawords.yml.dist mediawords.yml
    # Create PostgreSQL database
    - ./install/create_default_db_user_and_databases.sh
before_script:
    # Initialize PostgreSQL database
    - ./script/run_with_carton.sh ./script/mediawords_create_db.pl
script:
    # Run Media Cloud's test suite, report test coverage to https://coveralls.io/r/berkmancenter/mediacloud
    - ./script/run_test_suite_for_devel_cover.sh coveralls --destroy-solr
